# DATASET SACADO DE KAGGLE (https://www.kaggle.com/datasets/eoinamoore/historical-nba-data-and-player-box-scores)

In [1]:
# Librerías
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import os
os.getcwd()

# Configurar visualización amplia 
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_width_chars(300)
pl.Config.set_fmt_str_lengths(150)
pl.Config.set_tbl_rows(10)

polars.config.Config

### Cargamos el Dataset como LazyFrame

In [2]:
# Install dependencies as needed:
# pip install kagglehub[polars-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Players.csv"

# Load the latest version
lf = kagglehub.load_dataset(
  KaggleDatasetAdapter.POLARS,
  "eoinamoore/historical-nba-data-and-player-box-scores",
  file_path,
)

print("First 5 records:", lf.collect().head())

/tmp/ipykernel_713789/1947884339.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  lf = kagglehub.load_dataset(

Downloading to /home/mateorzan/.cache/kagglehub/datasets/eoinamoore/historical-nba-data-and-player-box-scores/versions/398/Players.csv...

100%|██████████| 337k/337k [00:00<00:00, 713kB/s]

First 5 records: shape: (5, 14)
┌───────────┬───────────┬──────────────┬───────────┬─────────────────┬─────────┬──────────────┬───────────────┬───────┬─────────┬────────┬───────────┬────────────┬─────────────┐
│ personId  ┆ firstName ┆ lastName     ┆ birthDate ┆ school          ┆ country ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear ┆ draftRound ┆ draftNumber │
│ ---       ┆ ---       ┆ ---          ┆ ---       ┆ ---             ┆ ---     ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---       ┆ ---        ┆ ---         │
│ i64       ┆ str       ┆ str          ┆ str       ┆ str             ┆ str     ┆ i64          ┆ i64           ┆ str   ┆ str     ┆ str    ┆ i64       ┆ i64        ┆ i64         │
╞═══════════╪═══════════╪══════════════╪═══════════╪═════════════════╪═════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═══════════╪════════════╪═════════════╡
│ 196294534 ┆ Alberto   ┆ Abalde       ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 76001     ┆ Alaa      ┆ Abdelnaby    ┆ null      ┆ Duke            ┆ USA     ┆ 82           ┆ 240           ┆ 0     ┆ 1       ┆ 0      ┆ 1990      ┆ 1          ┆ 25          │
│ 76002     ┆ Zaid      ┆ Abdul-Aziz   ┆ null      ┆ Iowa State      ┆ USA     ┆ 81           ┆ 235           ┆ 0     ┆ 0       ┆ 1      ┆ 1968      ┆ 1          ┆ 5           │
│ 76003     ┆ Kareem    ┆ Abdul-Jabbar ┆ null      ┆ UCLA            ┆ USA     ┆ 86           ┆ 225           ┆ 0     ┆ 0       ┆ 1      ┆ 1969      ┆ 1          ┆ 1           │
│ 51        ┆ Mahmoud   ┆ Abdul-Rauf   ┆ null      ┆ Louisiana State ┆ USA     ┆ 73           ┆ 162           ┆ 1     ┆ 0       ┆ 0      ┆ 1990      ┆ 1          ┆ 3           │
└───────────┴───────────┴──────────────┴───────────┴─────────────────┴─────────┴──────────────┴───────────────┴───────┴─────────┴────────┴───────────┴────────────┴─────────────┘

### Analisis de Datos

In [3]:
# Visualizamos los datos con LazyFrame
lf.collect()

shape: (6_683, 14)
┌────────────┬──────────────┬──────────────┬───────────┬─────────────────┬─────────┬──────────────┬───────────────┬───────┬─────────┬────────┬───────────┬────────────┬─────────────┐
│ personId   ┆ firstName    ┆ lastName     ┆ birthDate ┆ school          ┆ country ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear ┆ draftRound ┆ draftNumber │
│ ---        ┆ ---          ┆ ---          ┆ ---       ┆ ---             ┆ ---     ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---       ┆ ---        ┆ ---         │
│ i64        ┆ str          ┆ str          ┆ str       ┆ str             ┆ str     ┆ i64          ┆ i64           ┆ str   ┆ str     ┆ str    ┆ i64       ┆ i64        ┆ i64         │
╞════════════╪══════════════╪══════════════╪═══════════╪═════════════════╪═════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═══════════╪════════════╪═════════════╡
│ 196294534  ┆ Alberto      ┆ Abalde       ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 76001      ┆ Alaa         ┆ Abdelnaby    ┆ null      ┆ Duke            ┆ USA     ┆ 82           ┆ 240           ┆ 0     ┆ 1       ┆ 0      ┆ 1990      ┆ 1          ┆ 25          │
│ 76002      ┆ Zaid         ┆ Abdul-Aziz   ┆ null      ┆ Iowa State      ┆ USA     ┆ 81           ┆ 235           ┆ 0     ┆ 0       ┆ 1      ┆ 1968      ┆ 1          ┆ 5           │
│ 76003      ┆ Kareem       ┆ Abdul-Jabbar ┆ null      ┆ UCLA            ┆ USA     ┆ 86           ┆ 225           ┆ 0     ┆ 0       ┆ 1      ┆ 1969      ┆ 1          ┆ 1           │
│ 51         ┆ Mahmoud      ┆ Abdul-Rauf   ┆ null      ┆ Louisiana State ┆ USA     ┆ 73           ┆ 162           ┆ 1     ┆ 0       ┆ 0      ┆ 1990      ┆ 1          ┆ 3           │
│ …          ┆ …            ┆ …            ┆ …         ┆ …               ┆ …       ┆ …            ┆ …             ┆ …     ┆ …       ┆ …      ┆ …         ┆ …          ┆ …           │
│ 1962936150 ┆ Maurillioh   ┆ de Rosa      ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 560        ┆ de la Fuente ┆ de la Fuente ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 1642365    ┆ Nikola       ┆ Đurisic      ┆ null      ┆ Mega Basket     ┆ Belgium ┆ 80           ┆ 214           ┆ 1     ┆ 0       ┆ 0      ┆ 2024      ┆ 2          ┆ 43          │
│ 196294611  ┆ Olivinha     ┆ null         ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 43217      ┆ Olivinha     ┆ null         ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
└────────────┴──────────────┴──────────────┴───────────┴─────────────────┴─────────┴──────────────┴───────────────┴───────┴─────────┴────────┴───────────┴────────────┴─────────────┘

In [4]:
lf.schema

/tmp/ipykernel_713789/2177650233.py:1: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  lf.schema

Schema([('personId', Int64),
        ('firstName', String),
        ('lastName', String),
        ('birthDate', String),
        ('school', String),
        ('country', String),
        ('heightInches', Int64),
        ('bodyWeightLbs', Int64),
        ('guard', String),
        ('forward', String),
        ('center', String),
        ('draftYear', Int64),
        ('draftRound', Int64),
        ('draftNumber', Int64)])

In [5]:
lf.describe()

shape: (9, 15)
┌────────────┬────────────┬──────────────┬──────────┬───────────┬─────────────────────────────────────┬───────────┬──────────────┬───────────────┬───────┬─────────┬────────┬─────────────┬────────────┬─────────────┐
│ statistic  ┆ personId   ┆ firstName    ┆ lastName ┆ birthDate ┆ school                              ┆ country   ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear   ┆ draftRound ┆ draftNumber │
│ ---        ┆ ---        ┆ ---          ┆ ---      ┆ ---       ┆ ---                                 ┆ ---       ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---         ┆ ---        ┆ ---         │
│ str        ┆ f64        ┆ str          ┆ str      ┆ str       ┆ str                                 ┆ str       ┆ f64          ┆ f64           ┆ str   ┆ str     ┆ str    ┆ f64         ┆ f64        ┆ f64         │
╞════════════╪════════════╪══════════════╪══════════╪═══════════╪═════════════════════════════════════╪═══════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═════════════╪════════════╪═════════════╡
│ count      ┆ 6683.0     ┆ 6682         ┆ 6681     ┆ 0         ┆ 4616                                ┆ 4726      ┆ 4569.0       ┆ 4563.0        ┆ 5038  ┆ 5038    ┆ 5038   ┆ 4642.0      ┆ 4480.0     ┆ 4422.0      │
│ null_count ┆ 0.0        ┆ 1            ┆ 2        ┆ 6683      ┆ 2067                                ┆ 1957      ┆ 2114.0       ┆ 2120.0        ┆ 1645  ┆ 1645    ┆ 1645   ┆ 2041.0      ┆ 2203.0     ┆ 2261.0      │
│ mean       ┆ 4.3601e7   ┆ null         ┆ null     ┆ null      ┆ null                                ┆ null      ┆ 78.052747    ┆ 210.998685    ┆ null  ┆ null    ┆ null   ┆ 1419.389056 ┆ -0.365625  ┆ 21.26142    │
│ std        ┆ 2.7234e8   ┆ null         ┆ null     ┆ null      ┆ null                                ┆ null      ┆ 3.624273     ┆ 27.05438      ┆ null  ┆ null    ┆ null   ┆ 899.925763  ┆ 6.475935   ┆ 31.19699    │
│ min        ┆ 2.0        ┆ A.C.         ┆ Abalde   ┆ null      ┆                                     ┆ Anla      ┆ 63.0         ┆ 133.0         ┆ 0     ┆ 0       ┆ 0      ┆ -22.0       ┆ -22.0      ┆ -22.0       │
│ 25%        ┆ 56089.0    ┆ null         ┆ null     ┆ null      ┆ null                                ┆ null      ┆ 75.0         ┆ 190.0         ┆ null  ┆ null    ┆ null   ┆ -1.0        ┆ -1.0       ┆ -1.0        │
│ 50%        ┆ 77925.0    ┆ null         ┆ null     ┆ null      ┆ null                                ┆ null      ┆ 78.0         ┆ 210.0         ┆ null  ┆ null    ┆ null   ┆ 1976.0      ┆ 1.0        ┆ 14.0        │
│ 75%        ┆ 1.626168e6 ┆ null         ┆ null     ┆ null      ┆ null                                ┆ null      ┆ 81.0         ┆ 230.0         ┆ null  ┆ null    ┆ null   ┆ 1997.0      ┆ 2.0        ┆ 36.0        │
│ max        ┆ 1.9669e9   ┆ de la Fuente ┆ Đurisic  ┆ null      ┆ Znicz Pruszkow                      ┆ Venezuela ┆ 91.0         ┆ 360.0         ┆ false ┆ false   ┆ false  ┆ 2025.0      ┆ 20.0       ┆ 221.0       │
└────────────┴────────────┴──────────────┴──────────┴───────────┴─────────────────────────────────────┴───────────┴──────────────┴───────────────┴───────┴─────────┴────────┴─────────────┴────────────┴─────────────┘

In [6]:
lf.null_count().collect()

shape: (1, 14)
┌──────────┬───────────┬──────────┬───────────┬────────┬─────────┬──────────────┬───────────────┬───────┬─────────┬────────┬───────────┬────────────┬─────────────┐
│ personId ┆ firstName ┆ lastName ┆ birthDate ┆ school ┆ country ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear ┆ draftRound ┆ draftNumber │
│ ---      ┆ ---       ┆ ---      ┆ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---       ┆ ---        ┆ ---         │
│ u32      ┆ u32       ┆ u32      ┆ u32       ┆ u32    ┆ u32     ┆ u32          ┆ u32           ┆ u32   ┆ u32     ┆ u32    ┆ u32       ┆ u32        ┆ u32         │
╞══════════╪═══════════╪══════════╪═══════════╪════════╪═════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═══════════╪════════════╪═════════════╡
│ 0        ┆ 1         ┆ 2        ┆ 6683      ┆ 2067   ┆ 1957    ┆ 2114         ┆ 2120          ┆ 1645  ┆ 1645    ┆ 1645   ┆ 2041      ┆ 2203       ┆ 2261        │
└──────────┴───────────┴──────────┴───────────┴────────┴─────────┴──────────────┴───────────────┴───────┴─────────┴────────┴───────────┴────────────┴─────────────┘

In [7]:
# Filtrar filas con al menos un nulo
filas_con_nulos = lf.filter(
    pl.any_horizontal(pl.all().is_null())
)

# Ejecutar y ver resultado (primeras 10 filas, por ejemplo)
print(filas_con_nulos.collect())

shape: (6_683, 14)
┌────────────┬──────────────┬──────────────┬───────────┬─────────────────┬─────────┬──────────────┬───────────────┬───────┬─────────┬────────┬───────────┬────────────┬─────────────┐
│ personId   ┆ firstName    ┆ lastName     ┆ birthDate ┆ school          ┆ country ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear ┆ draftRound ┆ draftNumber │
│ ---        ┆ ---          ┆ ---          ┆ ---       ┆ ---             ┆ ---     ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---       ┆ ---        ┆ ---         │
│ i64        ┆ str          ┆ str          ┆ str       ┆ str             ┆ str     ┆ i64          ┆ i64           ┆ str   ┆ str     ┆ str    ┆ i64       ┆ i64        ┆ i64         │
╞════════════╪══════════════╪══════════════╪═══════════╪═════════════════╪═════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═══════════╪════════════╪═════════════╡
│ 196294534  ┆ Alberto      ┆ Abalde       ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 76001      ┆ Alaa         ┆ Abdelnaby    ┆ null      ┆ Duke            ┆ USA     ┆ 82           ┆ 240           ┆ 0     ┆ 1       ┆ 0      ┆ 1990      ┆ 1          ┆ 25          │
│ 76002      ┆ Zaid         ┆ Abdul-Aziz   ┆ null      ┆ Iowa State      ┆ USA     ┆ 81           ┆ 235           ┆ 0     ┆ 0       ┆ 1      ┆ 1968      ┆ 1          ┆ 5           │
│ 76003      ┆ Kareem       ┆ Abdul-Jabbar ┆ null      ┆ UCLA            ┆ USA     ┆ 86           ┆ 225           ┆ 0     ┆ 0       ┆ 1      ┆ 1969      ┆ 1          ┆ 1           │
│ 51         ┆ Mahmoud      ┆ Abdul-Rauf   ┆ null      ┆ Louisiana State ┆ USA     ┆ 73           ┆ 162           ┆ 1     ┆ 0       ┆ 0      ┆ 1990      ┆ 1          ┆ 3           │
│ …          ┆ …            ┆ …            ┆ …         ┆ …               ┆ …       ┆ …            ┆ …             ┆ …     ┆ …       ┆ …      ┆ …         ┆ …          ┆ …           │
│ 1962936150 ┆ Maurillioh   ┆ de Rosa      ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 560        ┆ de la Fuente ┆ de la Fuente ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 1642365    ┆ Nikola       ┆ Đurisic      ┆ null      ┆ Mega Basket     ┆ Belgium ┆ 80           ┆ 214           ┆ 1     ┆ 0       ┆ 0      ┆ 2024      ┆ 2          ┆ 43          │
│ 196294611  ┆ Olivinha     ┆ null         ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 43217      ┆ Olivinha     ┆ null         ┆ null      ┆ null            ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
└────────────┴──────────────┴──────────────┴───────────┴─────────────────┴─────────┴──────────────┴───────────────┴───────┴─────────┴────────┴───────────┴────────────┴─────────────┘

### Creamos el Dataframe para limpiarlo

In [8]:
df_players = lf.collect()
df_players.head(2)

shape: (2, 14)
┌───────────┬───────────┬───────────┬───────────┬────────┬─────────┬──────────────┬───────────────┬───────┬─────────┬────────┬───────────┬────────────┬─────────────┐
│ personId  ┆ firstName ┆ lastName  ┆ birthDate ┆ school ┆ country ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear ┆ draftRound ┆ draftNumber │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---       ┆ ---        ┆ ---         │
│ i64       ┆ str       ┆ str       ┆ str       ┆ str    ┆ str     ┆ i64          ┆ i64           ┆ str   ┆ str     ┆ str    ┆ i64       ┆ i64        ┆ i64         │
╞═══════════╪═══════════╪═══════════╪═══════════╪════════╪═════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═══════════╪════════════╪═════════════╡
│ 196294534 ┆ Alberto   ┆ Abalde    ┆ null      ┆ null   ┆ null    ┆ null         ┆ null          ┆ null  ┆ null    ┆ null   ┆ null      ┆ null       ┆ null        │
│ 76001     ┆ Alaa      ┆ Abdelnaby ┆ null      ┆ Duke   ┆ USA     ┆ 82           ┆ 240           ┆ 0     ┆ 1       ┆ 0      ┆ 1990      ┆ 1          ┆ 25          │
└───────────┴───────────┴───────────┴───────────┴────────┴─────────┴──────────────┴───────────────┴───────┴─────────┴────────┴───────────┴────────────┴─────────────┘

In [10]:
# Columnas a eliminar que no aportan información relevante para el análisis
columnas_a_eliminar = ["birthDate"]

df_players = df_players.drop(columnas_a_eliminar)

In [ ]:
# Eliminamos todos los nulos ya que vemos que la mayoria de nulos son jugadores que no tienen datos de altura, peso, posición, etc. y no aportan información relevante para el análisis.

df_players = df_players.drop_nulls()
df_players.null_count()

shape: (1, 13)
┌──────────┬───────────┬──────────┬────────┬─────────┬──────────────┬───────────────┬───────┬─────────┬────────┬───────────┬────────────┬─────────────┐
│ personId ┆ firstName ┆ lastName ┆ school ┆ country ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear ┆ draftRound ┆ draftNumber │
│ ---      ┆ ---       ┆ ---      ┆ ---    ┆ ---     ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---       ┆ ---        ┆ ---         │
│ u32      ┆ u32       ┆ u32      ┆ u32    ┆ u32     ┆ u32          ┆ u32           ┆ u32   ┆ u32     ┆ u32    ┆ u32       ┆ u32        ┆ u32         │
╞══════════╪═══════════╪══════════╪════════╪═════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═══════════╪════════════╪═════════════╡
│ 0        ┆ 0         ┆ 0        ┆ 0      ┆ 0       ┆ 0            ┆ 0             ┆ 0     ┆ 0       ┆ 0      ┆ 0         ┆ 0          ┆ 0           │
└──────────┴───────────┴──────────┴────────┴─────────┴──────────────┴───────────────┴───────┴─────────┴────────┴───────────┴────────────┴─────────────┘

In [15]:
df_players.describe()

shape: (9, 14)
┌────────────┬───────────────┬───────────┬───────────┬─────────────────────────────────────┬───────────┬──────────────┬───────────────┬───────┬─────────┬────────┬─────────────┬────────────┬─────────────┐
│ statistic  ┆ personId      ┆ firstName ┆ lastName  ┆ school                              ┆ country   ┆ heightInches ┆ bodyWeightLbs ┆ guard ┆ forward ┆ center ┆ draftYear   ┆ draftRound ┆ draftNumber │
│ ---        ┆ ---           ┆ ---       ┆ ---       ┆ ---                                 ┆ ---       ┆ ---          ┆ ---           ┆ ---   ┆ ---     ┆ ---    ┆ ---         ┆ ---        ┆ ---         │
│ str        ┆ f64           ┆ str       ┆ str       ┆ str                                 ┆ str       ┆ f64          ┆ f64           ┆ str   ┆ str     ┆ str    ┆ f64         ┆ f64        ┆ f64         │
╞════════════╪═══════════════╪═══════════╪═══════════╪═════════════════════════════════════╪═══════════╪══════════════╪═══════════════╪═══════╪═════════╪════════╪═════════════╪════════════╪═════════════╡
│ count      ┆ 4272.0        ┆ 4272      ┆ 4272      ┆ 4272                                ┆ 4272      ┆ 4272.0       ┆ 4272.0        ┆ 4272  ┆ 4272    ┆ 4272   ┆ 4272.0      ┆ 4272.0     ┆ 4272.0      │
│ null_count ┆ 0.0           ┆ 0         ┆ 0         ┆ 0                                   ┆ 0         ┆ 0.0          ┆ 0.0           ┆ 0     ┆ 0       ┆ 0      ┆ 0.0         ┆ 0.0        ┆ 0.0         │
│ mean       ┆ 262918.261938 ┆ null      ┆ null      ┆ null                                ┆ null      ┆ 78.164794    ┆ 211.755618    ┆ null  ┆ null    ┆ null   ┆ 1440.291901 ┆ 0.124532   ┆ 22.542135   │
│ std        ┆ 507817.963751 ┆ null      ┆ null      ┆ null                                ┆ null      ┆ 3.622104     ┆ 27.222889     ┆ null  ┆ null    ┆ null   ┆ 890.51875   ┆ 5.617558   ┆ 30.866896   │
│ min        ┆ 2.0           ┆ A.C.      ┆ Abdelnaby ┆                                     ┆ Anla      ┆ 63.0         ┆ 133.0         ┆ 0     ┆ 0       ┆ 0      ┆ -22.0       ┆ -22.0      ┆ -22.0       │
│ 25%        ┆ 2753.0        ┆ null      ┆ null      ┆ null                                ┆ null      ┆ 75.0         ┆ 190.0         ┆ null  ┆ null    ┆ null   ┆ -1.0        ┆ -1.0       ┆ -1.0        │
│ 50%        ┆ 77399.0       ┆ null      ┆ null      ┆ null                                ┆ null      ┆ 78.0         ┆ 210.0         ┆ null  ┆ null    ┆ null   ┆ 1978.0      ┆ 1.0        ┆ 16.0        │
│ 75%        ┆ 200840.0      ┆ null      ┆ null      ┆ null                                ┆ null      ┆ 81.0         ┆ 230.0         ┆ null  ┆ null    ┆ null   ┆ 1998.0      ┆ 2.0        ┆ 37.0        │
│ max        ┆ 1.642862e6    ┆ Zylan     ┆ Đurisic   ┆ Znicz Pruszkow                      ┆ Venezuela ┆ 91.0         ┆ 360.0         ┆ 1     ┆ 1       ┆ 1      ┆ 2025.0      ┆ 20.0       ┆ 221.0       │
└────────────┴───────────────┴───────────┴───────────┴─────────────────────────────────────┴───────────┴──────────────┴───────────────┴───────┴─────────┴────────┴─────────────┴────────────┴─────────────┘

In [16]:
df_players.is_duplicated().sum()

0