# DATASET SACADO DE KAGGLE (https://www.kaggle.com/datasets/eoinamoore/historical-nba-data-and-player-box-scores)

In [9]:
# Librerías
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import os
os.getcwd()

# Configurar visualización amplia 
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_width_chars(300)
pl.Config.set_fmt_str_lengths(150)
pl.Config.set_tbl_rows(10)

polars.config.Config

### Cargamos el Dataset como LazyFrame

In [10]:
# Install dependencies as needed:
# pip install kagglehub[polars-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "TeamStatisticsAdvanced.csv"

# Load the latest version
lf = kagglehub.load_dataset(
  KaggleDatasetAdapter.POLARS,
  "eoinamoore/historical-nba-data-and-player-box-scores",
  file_path,
  
)

print("First 5 records:", lf.collect().head())

/tmp/ipykernel_659435/4091882800.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  lf = kagglehub.load_dataset(

First 5 records: shape: (5, 38)
┌─────┬────────┬────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬─────┬─────┐
│ gam ┆ teamId ┆ teamCi ┆ teamNa ┆ gameTy ┆ astPc ┆ astRa ┆ astTo ┆ avail ┆ defRa ┆ drebP ┆ eDefR ┆ eNetR ┆ eOffR ┆ ePace ┆ efgPc ┆ gameD ┆ gameD ┆ home ┆ match ┆ min  ┆ netRa ┆ offRa ┆ oppon ┆ oppon ┆ oppon ┆ orebP ┆ pace  ┆ paceP ┆ pie   ┆ poss ┆ rebPc ┆ teamA ┆ teamN ┆ tmTov ┆ tsPct ┆ win ┆ wl  │
│ eId ┆ ---    ┆ ty     ┆ me     ┆ pe     ┆ t     ┆ tio   ┆ ---   ┆ ableF ┆ ting  ┆ ct    ┆ ating ┆ ating ┆ ating ┆ ---   ┆ t     ┆ ate   ┆ ateTi ┆ ---  ┆ up    ┆ ---  ┆ ting  ┆ ting  ┆ entTe ┆ entTe ┆ entTe ┆ ct    ┆ ---   ┆ er40  ┆ ---   ┆ ---  ┆ t     ┆ bbrev ┆ ame_r ┆ Pct   ┆ ---   ┆ --- ┆ --- │
│ --- ┆ i64    ┆ ---    ┆ ---    ┆ ---    ┆ ---   ┆ ---   ┆ f64   ┆ lag   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ f64   ┆ ---   ┆ ---   ┆ meEst ┆ i64  ┆ ---   ┆ f64  ┆ ---   ┆ ---   ┆ amCit ┆ amId  ┆ amNam ┆ ---   ┆ f64   ┆ ---   ┆ f64   ┆ i64  ┆ ---   ┆ iatio ┆ ight  ┆ ---   ┆ f64   ┆ i64 ┆ str │
│ i64 ┆        ┆ str    ┆ str    ┆ str    ┆ f64   ┆ f64   ┆       ┆ ---   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆       ┆ f64   ┆ str   ┆ ---   ┆      ┆ str   ┆      ┆ f64   ┆ f64   ┆ y     ┆ ---   ┆ e     ┆ f64   ┆       ┆ f64   ┆       ┆      ┆ f64   ┆ n     ┆ ---   ┆ f64   ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆ i64   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   ┆      ┆       ┆      ┆       ┆       ┆ ---   ┆ i64   ┆ ---   ┆       ┆       ┆       ┆       ┆      ┆       ┆ ---   ┆ str   ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆      ┆       ┆       ┆ str   ┆       ┆ str   ┆       ┆       ┆       ┆       ┆      ┆       ┆ str   ┆       ┆       ┆       ┆     ┆     │
╞═════╪════════╪════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═════╪═════╡
│ 225 ┆ 161061 ┆ Detroi ┆ Piston ┆ Regula ┆ 0.705 ┆ 23.3  ┆ 2.38  ┆ 1     ┆ 84.2  ┆ 0.736 ┆ 84.7  ┆ 40.1  ┆ 124.7 ┆ 94.5  ┆ 0.633 ┆ 2026- ┆ 2026- ┆ 1    ┆ DET   ┆ 48.0 ┆ 42.7  ┆ 126.9 ┆ New   ┆ 16106 ┆ Knick ┆ 0.225 ┆ 94.0  ┆ 78.33 ┆ 0.708 ┆ 93   ┆ 0.516 ┆ DET   ┆ null  ┆ 0.14  ┆ 0.658 ┆ 1   ┆ W   │
│ 007 ┆ 2765   ┆ t      ┆ s      ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ York  ┆ 12752 ┆ s     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 42  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 19:30 ┆      ┆ NYK   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ Portla ┆ Trail  ┆ Regula ┆ 0.633 ┆ 20.9  ┆ 1.72  ┆ 1     ┆ 110.6 ┆ 0.735 ┆ 111.4 ┆ 16.9  ┆ 128.3 ┆ 104.2 ┆ 0.639 ┆ 2026- ┆ 2026- ┆ 1    ┆ POR   ┆ 48.0 ┆ 19.2  ┆ 129.8 ┆ Memph ┆ 16106 ┆ Grizz ┆ 0.31  ┆ 104.0 ┆ 86.67 ┆ 0.578 ┆ 104  ┆ 0.538 ┆ POR   ┆ null  ┆ 0.173 ┆ 0.68  ┆ 1   ┆ W   │
│ 007 ┆ 2757   ┆ nd     ┆ Blazer ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ is    ┆ 12763 ┆ lies  ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 45  ┆        ┆        ┆ s      ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆ MEM   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ New    ┆ Pelica ┆ Regula ┆ 0.674 ┆ 21.2  ┆ 1.81  ┆ 1     ┆ 118.6 ┆ 0.61  ┆ 119.2 ┆ 0.1   ┆ 119.4 ┆ 98.1  ┆ 0.631 ┆ 2026- ┆ 2026- ┆ 0    ┆ NOP @ ┆ 48.0 ┆ 4.1   ┆ 122.7 ┆ Minne ┆ 16106 ┆ Timbe ┆ 0.282 ┆ 97.0  ┆ 80.83 ┆ 0.54  ┆ 97   ┆ 0.48  ┆ NOP   ┆ null  ┆ 0.165 ┆ 0.663 ┆ 1   ┆ W   │
│ 007 ┆ 2740   ┆ Orlean ┆ ns     ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ MIN   ┆      ┆       ┆       ┆ sota  ┆ 12750 ┆ rwolv ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 44  ┆        ┆ s      ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 20:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆ es    ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ LA     ┆ Clippe ┆ Regula ┆ 0.595 ┆ 16.9  ┆ 1.38  ┆ 1     ┆ 114.4 ┆ 0.679 ┆ 110.3 ┆ 6.3   ┆ 116.5 ┆ 99.3  ┆ 0.585 ┆ 2026- ┆ 2026- ┆ 0    ┆ LAC @ ┆ 48.0 ┆ 0.7   ┆ 115.2 ┆ Sacra ┆ 16106 ┆ Kings ┆ 0.225 ┆ 98.0  ┆ 81.67 ┆ 0.537 ┆ 99   ┆ 0.484 ┆ LAC   ┆ null  ┆ 0.162 ┆ 0.656 ┆ 1   ┆ W   │
│ 007 ┆ 2746   ┆        ┆ rs     ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ SAC   ┆      ┆       ┆       ┆ mento ┆ 12758 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 46  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ Indian ┆ Pacers ┆ Regula ┆ 0.743 ┆ 20.6  ┆ 2.89  ┆ 1     ┆ 114.1 ┆ 0.654 ┆ 108.7 ┆ -1.3  ┆ 107.3 ┆ 94.4  ┆ 0.519 ┆ 2026- ┆ 2026- ┆ 0    ┆ IND @ ┆ 48.0 ┆ -7.7  ┆ 106.5 ┆ Milwa ┆ 16106 ┆ Bucks ┆ 0.152 ┆ 92.5  ┆ 77.08 ┆ 0.513 ┆ 93   ┆ 0.418 ┆ IND   ┆ null  ┆ 0.097 ┆ 0.561 ┆ 0   ┆ L   │
│ 007 ┆ 2754   ┆ a      ┆        ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ MIL   ┆      ┆       ┆       ┆ ukee  ┆ 12749 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 43  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 20:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
└─────┴────────┴────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴─────┴─────┘

### Analisis de Datos

In [11]:
# Visualizamos los datos con LazyFrame
lf.collect()

shape: (10_258, 38)
┌─────┬────────┬────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬─────┬─────┐
│ gam ┆ teamId ┆ teamCi ┆ teamNa ┆ gameTy ┆ astPc ┆ astRa ┆ astTo ┆ avail ┆ defRa ┆ drebP ┆ eDefR ┆ eNetR ┆ eOffR ┆ ePace ┆ efgPc ┆ gameD ┆ gameD ┆ home ┆ match ┆ min  ┆ netRa ┆ offRa ┆ oppon ┆ oppon ┆ oppon ┆ orebP ┆ pace  ┆ paceP ┆ pie   ┆ poss ┆ rebPc ┆ teamA ┆ teamN ┆ tmTov ┆ tsPct ┆ win ┆ wl  │
│ eId ┆ ---    ┆ ty     ┆ me     ┆ pe     ┆ t     ┆ tio   ┆ ---   ┆ ableF ┆ ting  ┆ ct    ┆ ating ┆ ating ┆ ating ┆ ---   ┆ t     ┆ ate   ┆ ateTi ┆ ---  ┆ up    ┆ ---  ┆ ting  ┆ ting  ┆ entTe ┆ entTe ┆ entTe ┆ ct    ┆ ---   ┆ er40  ┆ ---   ┆ ---  ┆ t     ┆ bbrev ┆ ame_r ┆ Pct   ┆ ---   ┆ --- ┆ --- │
│ --- ┆ i64    ┆ ---    ┆ ---    ┆ ---    ┆ ---   ┆ ---   ┆ f64   ┆ lag   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ f64   ┆ ---   ┆ ---   ┆ meEst ┆ i64  ┆ ---   ┆ f64  ┆ ---   ┆ ---   ┆ amCit ┆ amId  ┆ amNam ┆ ---   ┆ f64   ┆ ---   ┆ f64   ┆ i64  ┆ ---   ┆ iatio ┆ ight  ┆ ---   ┆ f64   ┆ i64 ┆ str │
│ i64 ┆        ┆ str    ┆ str    ┆ str    ┆ f64   ┆ f64   ┆       ┆ ---   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆       ┆ f64   ┆ str   ┆ ---   ┆      ┆ str   ┆      ┆ f64   ┆ f64   ┆ y     ┆ ---   ┆ e     ┆ f64   ┆       ┆ f64   ┆       ┆      ┆ f64   ┆ n     ┆ ---   ┆ f64   ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆ i64   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   ┆      ┆       ┆      ┆       ┆       ┆ ---   ┆ i64   ┆ ---   ┆       ┆       ┆       ┆       ┆      ┆       ┆ ---   ┆ str   ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆      ┆       ┆       ┆ str   ┆       ┆ str   ┆       ┆       ┆       ┆       ┆      ┆       ┆ str   ┆       ┆       ┆       ┆     ┆     │
╞═════╪════════╪════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═════╪═════╡
│ 225 ┆ 161061 ┆ Detroi ┆ Piston ┆ Regula ┆ 0.705 ┆ 23.3  ┆ 2.38  ┆ 1     ┆ 84.2  ┆ 0.736 ┆ 84.7  ┆ 40.1  ┆ 124.7 ┆ 94.5  ┆ 0.633 ┆ 2026- ┆ 2026- ┆ 1    ┆ DET   ┆ 48.0 ┆ 42.7  ┆ 126.9 ┆ New   ┆ 16106 ┆ Knick ┆ 0.225 ┆ 94.0  ┆ 78.33 ┆ 0.708 ┆ 93   ┆ 0.516 ┆ DET   ┆ null  ┆ 0.14  ┆ 0.658 ┆ 1   ┆ W   │
│ 007 ┆ 2765   ┆ t      ┆ s      ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ York  ┆ 12752 ┆ s     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 42  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 19:30 ┆      ┆ NYK   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ Portla ┆ Trail  ┆ Regula ┆ 0.633 ┆ 20.9  ┆ 1.72  ┆ 1     ┆ 110.6 ┆ 0.735 ┆ 111.4 ┆ 16.9  ┆ 128.3 ┆ 104.2 ┆ 0.639 ┆ 2026- ┆ 2026- ┆ 1    ┆ POR   ┆ 48.0 ┆ 19.2  ┆ 129.8 ┆ Memph ┆ 16106 ┆ Grizz ┆ 0.31  ┆ 104.0 ┆ 86.67 ┆ 0.578 ┆ 104  ┆ 0.538 ┆ POR   ┆ null  ┆ 0.173 ┆ 0.68  ┆ 1   ┆ W   │
│ 007 ┆ 2757   ┆ nd     ┆ Blazer ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ is    ┆ 12763 ┆ lies  ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 45  ┆        ┆        ┆ s      ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆ MEM   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ New    ┆ Pelica ┆ Regula ┆ 0.674 ┆ 21.2  ┆ 1.81  ┆ 1     ┆ 118.6 ┆ 0.61  ┆ 119.2 ┆ 0.1   ┆ 119.4 ┆ 98.1  ┆ 0.631 ┆ 2026- ┆ 2026- ┆ 0    ┆ NOP @ ┆ 48.0 ┆ 4.1   ┆ 122.7 ┆ Minne ┆ 16106 ┆ Timbe ┆ 0.282 ┆ 97.0  ┆ 80.83 ┆ 0.54  ┆ 97   ┆ 0.48  ┆ NOP   ┆ null  ┆ 0.165 ┆ 0.663 ┆ 1   ┆ W   │
│ 007 ┆ 2740   ┆ Orlean ┆ ns     ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ MIN   ┆      ┆       ┆       ┆ sota  ┆ 12750 ┆ rwolv ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 44  ┆        ┆ s      ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 20:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆ es    ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ LA     ┆ Clippe ┆ Regula ┆ 0.595 ┆ 16.9  ┆ 1.38  ┆ 1     ┆ 114.4 ┆ 0.679 ┆ 110.3 ┆ 6.3   ┆ 116.5 ┆ 99.3  ┆ 0.585 ┆ 2026- ┆ 2026- ┆ 0    ┆ LAC @ ┆ 48.0 ┆ 0.7   ┆ 115.2 ┆ Sacra ┆ 16106 ┆ Kings ┆ 0.225 ┆ 98.0  ┆ 81.67 ┆ 0.537 ┆ 99   ┆ 0.484 ┆ LAC   ┆ null  ┆ 0.162 ┆ 0.656 ┆ 1   ┆ W   │
│ 007 ┆ 2746   ┆        ┆ rs     ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ SAC   ┆      ┆       ┆       ┆ mento ┆ 12758 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 46  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ Indian ┆ Pacers ┆ Regula ┆ 0.743 ┆ 20.6  ┆ 2.89  ┆ 1     ┆ 114.1 ┆ 0.654 ┆ 108.7 ┆ -1.3  ┆ 107.3 ┆ 94.4  ┆ 0.519 ┆ 2026- ┆ 2026- ┆ 0    ┆ IND @ ┆ 48.0 ┆ -7.7  ┆ 106.5 ┆ Milwa ┆ 16106 ┆ Bucks ┆ 0.152 ┆ 92.5  ┆ 77.08 ┆ 0.513 ┆ 93   ┆ 0.418 ┆ IND   ┆ null  ┆ 0.097 ┆ 0.561 ┆ 0   ┆ L   │
│ 007 ┆ 2754   ┆ a      ┆        ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ MIL   ┆      ┆       ┆       ┆ ukee  ┆ 12749 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 43  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 20:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ …   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …    ┆ …     ┆ …    ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …    ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …   ┆ …   │
│ 125 ┆ 161061 ┆ New    ┆ Pelica ┆ Presea ┆ 0.5   ┆ 14.4  ┆ 1.25  ┆ 1     ┆ 95.1  ┆ 0.667 ┆ 92.6  ┆ 10.8  ┆ 103.3 ┆ 104.2 ┆ 0.489 ┆ 2025- ┆ 2025- ┆ 1    ┆ NOP   ┆ 48.0 ┆ 9.8   ┆ 104.9 ┆ Melbo ┆ 15016 ┆ Unite ┆ 0.321 ┆ 102.0 ┆ 85.0  ┆ 0.555 ┆ 102  ┆ 0.5   ┆ NOP   ┆ null  ┆ 0.157 ┆ 0.532 ┆ 1   ┆ W   │
│ 000 ┆ 2740   ┆ Orlean ┆ ns     ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-03 ┆ 10-03 ┆      ┆ vs.   ┆      ┆       ┆       ┆ urne  ┆       ┆ d     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 09  ┆        ┆ s      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 5:30: ┆      ┆ MEL   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ 00    ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 15016  ┆ Melbou ┆ United ┆ Presea ┆ 0.639 ┆ 16.0  ┆ 1.28  ┆ 1     ┆ 104.9 ┆ 0.679 ┆ 103.3 ┆ -10.8 ┆ 92.6  ┆ 104.2 ┆ 0.462 ┆ 2025- ┆ 2025- ┆ 0    ┆ MEL @ ┆ 48.0 ┆ -9.8  ┆ 95.1  ┆ New   ┆ 16106 ┆ Pelic ┆ 0.333 ┆ 102.0 ┆ 85.0  ┆ 0.445 ┆ 102  ┆ 0.5   ┆ MEL   ┆ null  ┆ 0.176 ┆ 0.486 ┆ 0   ┆ L   │
│ 000 ┆        ┆ rne    ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-03 ┆ 10-03 ┆      ┆ NOP   ┆      ┆       ┆       ┆ Orlea ┆ 12740 ┆ ans   ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 09  ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 5:30: ┆      ┆       ┆      ┆       ┆       ┆ ns    ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ 00    ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 161061 ┆ Los    ┆ Lakers ┆ Presea ┆ 0.435 ┆ 8.1   ┆ 0.45  ┆ 1     ┆ 100.0 ┆ 0.679 ┆ 95.9  ┆ -15.9 ┆ 80.0  ┆ 104.4 ┆ 0.351 ┆ 2025- ┆ 2025- ┆ 1    ┆ LAL   ┆ 48.0 ┆ -19.8 ┆ 80.2  ┆ Phoen ┆ 16106 ┆ Suns  ┆ 0.232 ┆ 102.0 ┆ 85.0  ┆ 0.329 ┆ 101  ┆ 0.455 ┆ LAL   ┆ null  ┆ 0.218 ┆ 0.449 ┆ 0   ┆ L   │
│ 000 ┆ 2747   ┆ Angele ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-03 ┆ 10-03 ┆      ┆ vs.   ┆      ┆       ┆       ┆ ix    ┆ 12756 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 01  ┆        ┆ s      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆ PHX   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 161061 ┆ New    ┆ Knicks ┆ Presea ┆ 0.543 ┆ 13.4  ┆ 1.12  ┆ 1     ┆ 82.4  ┆ 0.736 ┆ 82.3  ┆ 14.7  ┆ 97.0  ┆ 102.1 ┆ 0.429 ┆ 2025- ┆ 2025- ┆ 1    ┆ NYK @ ┆ 48.0 ┆ 15.7  ┆ 98.0  ┆ Phila ┆ 16106 ┆ 76ers ┆ 0.349 ┆ 101.5 ┆ 84.58 ┆ 0.571 ┆ 101  ┆ 0.526 ┆ NYK   ┆ null  ┆ 0.168 ┆ 0.471 ┆ 1   ┆ W   │
│ 000 ┆ 2752   ┆ York   ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-02 ┆ 10-02 ┆      ┆ PHI   ┆      ┆       ┆       ┆ delph ┆ 12755 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 08  ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 12:00 ┆      ┆       ┆      ┆       ┆       ┆ ia    ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 161061 ┆ Philad ┆ 76ers  ┆ Presea ┆ 0.63  ┆ 12.8  ┆ 0.85  ┆ 1     ┆ 98.0  ┆ 0.651 ┆ 97.0  ┆ -14.7 ┆ 82.3  ┆ 102.1 ┆ 0.365 ┆ 2025- ┆ 2025- ┆ 0    ┆ PHI @ ┆ 48.0 ┆ -15.7 ┆ 82.4  ┆ New   ┆ 16106 ┆ Knick ┆ 0.264 ┆ 101.5 ┆ 84.58 ┆ 0.429 ┆ 102  ┆ 0.474 ┆ PHI   ┆ null  ┆ 0.196 ┆ 0.456 ┆ 0   ┆ L   │
│ 000 ┆ 2755   ┆ elphia ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-02 ┆ 10-02 ┆      ┆ NYK   ┆      ┆       ┆       ┆ York  ┆ 12752 ┆ s     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 08  ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 12:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
└─────┴────────┴────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴─────┴─────┘

In [12]:
lf.schema

/tmp/ipykernel_659435/2177650233.py:1: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  lf.schema

Schema([('gameId', Int64),
        ('teamId', Int64),
        ('teamCity', String),
        ('teamName', String),
        ('gameType', String),
        ('astPct', Float64),
        ('astRatio', Float64),
        ('astTo', Float64),
        ('availableFlag', Int64),
        ('defRating', Float64),
        ('drebPct', Float64),
        ('eDefRating', Float64),
        ('eNetRating', Float64),
        ('eOffRating', Float64),
        ('ePace', Float64),
        ('efgPct', Float64),
        ('gameDate', String),
        ('gameDateTimeEst', String),
        ('home', Int64),
        ('matchup', String),
        ('min', Float64),
        ('netRating', Float64),
        ('offRating', Float64),
        ('opponentTeamCity', String),
        ('opponentTeamId', Int64),
        ('opponentTeamName', String),
        ('orebPct', Float64),
        ('pace', Float64),
        ('pacePer40', Float64),
        ('pie', Float64),
        ('poss', Int64),
        ('rebPct', Float64),
        ('teamAbbreviation', String),
        ('teamName_right', String),
        ('tmTovPct', Float64),
        ('tsPct', Float64),
        ('win', Int64),
        ('wl', String)])

In [13]:
lf.describe()

shape: (9, 39)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ sta ┆ gam ┆ tea ┆ tea ┆ tea ┆ gam ┆ ast ┆ astRat ┆ astTo ┆ avail ┆ defRa ┆ drebP ┆ eDefR ┆ eNetR ┆ eOffR ┆ ePace ┆ efgPc ┆ gameD ┆ gameD ┆ home  ┆ match ┆ min   ┆ netRa ┆ offRa ┆ oppon ┆ oppon ┆ oppon ┆ orebP ┆ pace  ┆ paceP ┆ pie   ┆ poss  ┆ rebPc ┆ teamA ┆ teamN ┆ tmTov ┆ tsPct ┆ win   ┆ wl    │
│ tis ┆ eId ┆ mId ┆ mCi ┆ mNa ┆ eTy ┆ Pct ┆ io     ┆ ---   ┆ ableF ┆ ting  ┆ ct    ┆ ating ┆ ating ┆ ating ┆ ---   ┆ t     ┆ ate   ┆ ateTi ┆ ---   ┆ up    ┆ ---   ┆ ting  ┆ ting  ┆ entTe ┆ entTe ┆ entTe ┆ ct    ┆ ---   ┆ er40  ┆ ---   ┆ ---   ┆ t     ┆ bbrev ┆ ame_r ┆ Pct   ┆ ---   ┆ ---   ┆ ---   │
│ tic ┆ --- ┆ --- ┆ ty  ┆ me  ┆ pe  ┆ --- ┆ ---    ┆ f64   ┆ lag   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ f64   ┆ ---   ┆ ---   ┆ meEst ┆ f64   ┆ ---   ┆ f64   ┆ ---   ┆ ---   ┆ amCit ┆ amId  ┆ amNam ┆ ---   ┆ f64   ┆ ---   ┆ f64   ┆ f64   ┆ ---   ┆ iatio ┆ ight  ┆ ---   ┆ f64   ┆ f64   ┆ str   │
│ --- ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64    ┆       ┆ ---   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆       ┆ f64   ┆ str   ┆ ---   ┆       ┆ str   ┆       ┆ f64   ┆ f64   ┆ y     ┆ ---   ┆ e     ┆ f64   ┆       ┆ f64   ┆       ┆       ┆ f64   ┆ n     ┆ ---   ┆ f64   ┆       ┆       ┆       │
│ str ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆        ┆       ┆ f64   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   ┆       ┆       ┆       ┆       ┆       ┆ ---   ┆ f64   ┆ ---   ┆       ┆       ┆       ┆       ┆       ┆       ┆ ---   ┆ str   ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   ┆       ┆ str   ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   ┆       ┆       ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ cou ┆ 102 ┆ 102 ┆ 999 ┆ 999 ┆ 102 ┆ 102 ┆ 10258. ┆ 10258 ┆ 5266. ┆ 10258 ┆ 9511. ┆ 10258 ┆ 10258 ┆ 10258 ┆ 10258 ┆ 10258 ┆ 10258 ┆ 9990  ┆ 9990. ┆ 10246 ┆ 10258 ┆ 10258 ┆ 10258 ┆ 9990  ┆ 9990. ┆ 9990  ┆ 9512. ┆ 10258 ┆ 10258 ┆ 10258 ┆ 10258 ┆ 8876. ┆ 10258 ┆ 0     ┆ 10258 ┆ 10258 ┆ 9990. ┆ 10254 │
│ nt  ┆ 58. ┆ 58. ┆ 0   ┆ 0   ┆ 58  ┆ 58. ┆ 0      ┆ .0    ┆ 0     ┆ .0    ┆ 0     ┆ .0    ┆ .0    ┆ .0    ┆ .0    ┆ .0    ┆       ┆       ┆ 0     ┆       ┆ .0    ┆ .0    ┆ .0    ┆       ┆ 0     ┆       ┆ 0     ┆ .0    ┆ .0    ┆ .0    ┆ .0    ┆ 0     ┆       ┆       ┆ .0    ┆ .0    ┆ 0     ┆       │
│     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ 0   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ nul ┆ 0.0 ┆ 0.0 ┆ 268 ┆ 268 ┆ 0   ┆ 0.0 ┆ 0.0    ┆ 0.0   ┆ 4992. ┆ 0.0   ┆ 747.0 ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 0     ┆ 268   ┆ 268.0 ┆ 12    ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 268   ┆ 268.0 ┆ 268   ┆ 746.0 ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 0.0   ┆ 1382. ┆ 0     ┆ 10258 ┆ 0.0   ┆ 0.0   ┆ 268.0 ┆ 4     │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆ 0     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0     ┆       ┆       ┆       ┆       ┆       ┆       │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ mea ┆ 2.7 ┆ 1.5 ┆ nul ┆ nul ┆ nul ┆ 0.5 ┆ 16.495 ┆ 1.589 ┆ 1.044 ┆ 105.6 ┆ 0.708 ┆ 103.9 ┆ 0.000 ┆ 103.9 ┆ 97.92 ┆ 0.502 ┆ null  ┆ null  ┆ 0.5   ┆ null  ┆ 48.21 ┆ 0.000 ┆ 105.6 ┆ null  ┆ 1.609 ┆ null  ┆ 0.291 ┆ 96.33 ┆ 80.27 ┆ 0.500 ┆ 96.75 ┆ 0.500 ┆ null  ┆ null  ┆ 0.158 ┆ 0.545 ┆ 0.5   ┆ null  │
│ n   ┆ 470 ┆ 897 ┆ l   ┆ l   ┆ l   ┆ 939 ┆ 028    ┆ 223   ┆ 056   ┆ 56288 ┆ 213   ┆ 67645 ┆ 127   ┆ 67752 ┆ 3669  ┆ 347   ┆       ┆       ┆       ┆       ┆ 4467  ┆ 702   ┆ 5699  ┆       ┆ 6e9   ┆       ┆ 806   ┆ 3847  ┆ 8148  ┆ 003   ┆ 1706  ┆ 005   ┆       ┆       ┆ 685   ┆ 457   ┆       ┆       │
│     ┆ e7  ┆ e9  ┆     ┆     ┆     ┆ 96  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ std ┆ 1.4 ┆ 1.8 ┆ nul ┆ nul ┆ nul ┆ 0.1 ┆ 3.2952 ┆ 0.733 ┆ 0.231 ┆ 12.75 ┆ 0.075 ┆ 12.69 ┆ 15.88 ┆ 12.69 ┆ 7.126 ┆ 0.071 ┆ null  ┆ null  ┆ 0.500 ┆ null  ┆ 1.690 ┆ 15.53 ┆ 12.76 ┆ null  ┆ 3.946 ┆ null  ┆ 0.075 ┆ 7.013 ┆ 5.844 ┆ 0.109 ┆ 7.650 ┆ 0.050 ┆ null  ┆ null  ┆ 0.044 ┆ 0.064 ┆ 0.500 ┆ null  │
│     ┆ 518 ┆ 221 ┆ l   ┆ l   ┆ l   ┆ 060 ┆ 51     ┆ 281   ┆ 342   ┆ 9455  ┆ 76    ┆ 1441  ┆ 9243  ┆ 1067  ┆ 793   ┆ 202   ┆       ┆       ┆ 025   ┆       ┆ 668   ┆ 4404  ┆ 075   ┆       ┆ 1e7   ┆       ┆ 771   ┆ 069   ┆ 187   ┆ 829   ┆ 913   ┆ 221   ┆       ┆       ┆ 672   ┆ 824   ┆ 025   ┆       │
│     ┆ e7  ┆ e8  ┆     ┆     ┆     ┆ 07  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ min ┆ 1.0 ┆ 41. ┆ Atl ┆ 76e ┆     ┆ 0.1 ┆ 4.1    ┆ 0.24  ┆ 0.0   ┆ 57.4  ┆ 0.432 ┆ 57.7  ┆ -73.5 ┆ 57.7  ┆ 77.0  ┆ 0.262 ┆ 1997- ┆ 1997- ┆ 0.0   ┆ ADL @ ┆ 24.0  ┆ -68.8 ┆ 57.4  ┆ Atlan ┆ 15016 ┆ 76ers ┆ 0.045 ┆ 75.0  ┆ 62.5  ┆ -0.17 ┆ 43.0  ┆ 0.304 ┆ ADL   ┆ null  ┆ 0.032 ┆ 0.316 ┆ 0.0   ┆ L     │
│     ┆ 300 ┆ 0   ┆ ant ┆ rs  ┆     ┆ 63  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 04-24 ┆ 04-24 ┆       ┆ OKC   ┆       ┆       ┆       ┆ ta    ┆ .0    ┆       ┆       ┆       ┆       ┆ 3     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 001 ┆     ┆ a   ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 19:00 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ e7  ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 25% ┆ 1.1 ┆ 1.6 ┆ nul ┆ nul ┆ nul ┆ 0.5 ┆ 14.2   ┆ 1.1   ┆ 1.0   ┆ 96.9  ┆ 0.658 ┆ 95.2  ┆ -10.4 ┆ 95.2  ┆ 92.9  ┆ 0.454 ┆ null  ┆ null  ┆ 0.0   ┆ null  ┆ 48.0  ┆ -9.8  ┆ 96.9  ┆ null  ┆ 1.610 ┆ null  ┆ 0.239 ┆ 91.5  ┆ 76.25 ┆ 0.429 ┆ 92.0  ┆ 0.466 ┆ null  ┆ null  ┆ 0.128 ┆ 0.501 ┆ 0.0   ┆ null  │
│     ┆ 600 ┆ 106 ┆ l   ┆ l   ┆ l   ┆ 25  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 6e9   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 086 ┆ e9  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ e7  ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 50% ┆ 2.2 ┆ 1.6 ┆ nul ┆ nul ┆ nul ┆ 0.5 ┆ 16.4   ┆ 1.44  ┆ 1.0   ┆ 105.4 ┆ 0.709 ┆ 103.7 ┆ 0.0   ┆ 103.7 ┆ 97.7  ┆ 0.5   ┆ null  ┆ null  ┆ 1.0   ┆ null  ┆ 48.0  ┆ 0.0   ┆ 105.4 ┆ null  ┆ 1.610 ┆ null  ┆ 0.291 ┆ 96.0  ┆ 80.0  ┆ 0.5   ┆ 97.0  ┆ 0.5   ┆ null  ┆ null  ┆ 0.156 ┆ 0.544 ┆ 1.0   ┆ null  │
│     ┆ 500 ┆ 106 ┆ l   ┆ l   ┆ l   ┆ 96  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 6e9   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 595 ┆ e9  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ e7  ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 75% ┆ 4.1 ┆ 1.6 ┆ nul ┆ nul ┆ nul ┆ 0.6 ┆ 18.8   ┆ 1.91  ┆ 1.0   ┆ 114.1 ┆ 0.761 ┆ 112.4 ┆ 10.4  ┆ 112.4 ┆ 102.9 ┆ 0.549 ┆ null  ┆ null  ┆ 1.0   ┆ null  ┆ 48.0  ┆ 9.8   ┆ 114.1 ┆ null  ┆ 1.610 ┆ null  ┆ 0.342 ┆ 101.0 ┆ 84.17 ┆ 0.571 ┆ 102.0 ┆ 0.534 ┆ null  ┆ null  ┆ 0.188 ┆ 0.588 ┆ 1.0   ┆ null  │
│     ┆ 300 ┆ 106 ┆ l   ┆ l   ┆ l   ┆ 67  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 6e9   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 156 ┆ e9  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ e7  ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ max ┆ 5.2 ┆ 1.6 ┆ Was ┆ Wiz ┆ Reg ┆ 0.9 ┆ 29.6   ┆ 8.33  ┆ 2.0   ┆ 158.7 ┆ 0.955 ┆ 154.7 ┆ 73.5  ┆ 154.7 ┆ 121.4 ┆ 0.765 ┆ 2026- ┆ 2026- ┆ 1.0   ┆ ZAK @ ┆ 68.0  ┆ 68.8  ┆ 158.7 ┆ Washi ┆ 1.610 ┆ Wizar ┆ 0.568 ┆ 123.7 ┆ 103.0 ┆ 1.173 ┆ 130.0 ┆ 0.696 ┆ ZAK   ┆ null  ┆ 0.388 ┆ 0.787 ┆ 1.0   ┆ W     │
│     ┆ 400 ┆ 106 ┆ hin ┆ ard ┆ ula ┆ 58  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆       ┆ WAS   ┆       ┆       ┆       ┆ ngton ┆ 6e9   ┆ ds    ┆       ┆ 1     ┆ 9     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 211 ┆ e9  ┆ gto ┆ s   ┆ r   ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ e7  ┆     ┆ n   ┆     ┆ Sea ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆ son ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [14]:
lf.null_count().collect()

shape: (1, 38)
┌────────┬────────┬────────┬────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬─────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬─────┬──────┬───────┬───────┬───────┬───────┬───────┬─────┬─────┐
│ gameId ┆ teamId ┆ teamCi ┆ teamNa ┆ gameTy ┆ astPct ┆ astRa ┆ astTo ┆ avail ┆ defRa ┆ drebP ┆ eDefR ┆ eNetR ┆ eOffR ┆ ePace ┆ efgPc ┆ gameD ┆ gameD ┆ home ┆ match ┆ min ┆ netRa ┆ offRa ┆ oppon ┆ oppon ┆ oppon ┆ orebP ┆ pace ┆ paceP ┆ pie ┆ poss ┆ rebPc ┆ teamA ┆ teamN ┆ tmTov ┆ tsPct ┆ win ┆ wl  │
│ ---    ┆ ---    ┆ ty     ┆ me     ┆ pe     ┆ ---    ┆ tio   ┆ ---   ┆ ableF ┆ ting  ┆ ct    ┆ ating ┆ ating ┆ ating ┆ ---   ┆ t     ┆ ate   ┆ ateTi ┆ ---  ┆ up    ┆ --- ┆ ting  ┆ ting  ┆ entTe ┆ entTe ┆ entTe ┆ ct    ┆ ---  ┆ er40  ┆ --- ┆ ---  ┆ t     ┆ bbrev ┆ ame_r ┆ Pct   ┆ ---   ┆ --- ┆ --- │
│ u32    ┆ u32    ┆ ---    ┆ ---    ┆ ---    ┆ u32    ┆ ---   ┆ u32   ┆ lag   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ u32   ┆ ---   ┆ ---   ┆ meEst ┆ u32  ┆ ---   ┆ u32 ┆ ---   ┆ ---   ┆ amCit ┆ amId  ┆ amNam ┆ ---   ┆ u32  ┆ ---   ┆ u32 ┆ u32  ┆ ---   ┆ iatio ┆ ight  ┆ ---   ┆ u32   ┆ u32 ┆ u32 │
│        ┆        ┆ u32    ┆ u32    ┆ u32    ┆        ┆ u32   ┆       ┆ ---   ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆       ┆ u32   ┆ u32   ┆ ---   ┆      ┆ u32   ┆     ┆ u32   ┆ u32   ┆ y     ┆ ---   ┆ e     ┆ u32   ┆      ┆ u32   ┆     ┆      ┆ u32   ┆ n     ┆ ---   ┆ u32   ┆       ┆     ┆     │
│        ┆        ┆        ┆        ┆        ┆        ┆       ┆       ┆ u32   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ u32   ┆      ┆       ┆     ┆       ┆       ┆ ---   ┆ u32   ┆ ---   ┆       ┆      ┆       ┆     ┆      ┆       ┆ ---   ┆ u32   ┆       ┆       ┆     ┆     │
│        ┆        ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆     ┆       ┆       ┆ u32   ┆       ┆ u32   ┆       ┆      ┆       ┆     ┆      ┆       ┆ u32   ┆       ┆       ┆       ┆     ┆     │
╞════════╪════════╪════════╪════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪═════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪═════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═════╪═════╡
│ 0      ┆ 0      ┆ 268    ┆ 268    ┆ 0      ┆ 0      ┆ 0     ┆ 0     ┆ 4992  ┆ 0     ┆ 747   ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 268   ┆ 268  ┆ 12    ┆ 0   ┆ 0     ┆ 0     ┆ 268   ┆ 268   ┆ 268   ┆ 746   ┆ 0    ┆ 0     ┆ 0   ┆ 0    ┆ 1382  ┆ 0     ┆ 10258 ┆ 0     ┆ 0     ┆ 268 ┆ 4   │
└────────┴────────┴────────┴────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴─────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴─────┴──────┴───────┴───────┴───────┴───────┴───────┴─────┴─────┘

In [15]:
# Filtrar filas con al menos un nulo
filas_con_nulos = lf.filter(
    pl.any_horizontal(pl.all().is_null())
)

# Ejecutar y ver resultado (primeras 10 filas, por ejemplo)
print(filas_con_nulos.collect())

shape: (10_258, 38)
┌─────┬────────┬────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬─────┬─────┐
│ gam ┆ teamId ┆ teamCi ┆ teamNa ┆ gameTy ┆ astPc ┆ astRa ┆ astTo ┆ avail ┆ defRa ┆ drebP ┆ eDefR ┆ eNetR ┆ eOffR ┆ ePace ┆ efgPc ┆ gameD ┆ gameD ┆ home ┆ match ┆ min  ┆ netRa ┆ offRa ┆ oppon ┆ oppon ┆ oppon ┆ orebP ┆ pace  ┆ paceP ┆ pie   ┆ poss ┆ rebPc ┆ teamA ┆ teamN ┆ tmTov ┆ tsPct ┆ win ┆ wl  │
│ eId ┆ ---    ┆ ty     ┆ me     ┆ pe     ┆ t     ┆ tio   ┆ ---   ┆ ableF ┆ ting  ┆ ct    ┆ ating ┆ ating ┆ ating ┆ ---   ┆ t     ┆ ate   ┆ ateTi ┆ ---  ┆ up    ┆ ---  ┆ ting  ┆ ting  ┆ entTe ┆ entTe ┆ entTe ┆ ct    ┆ ---   ┆ er40  ┆ ---   ┆ ---  ┆ t     ┆ bbrev ┆ ame_r ┆ Pct   ┆ ---   ┆ --- ┆ --- │
│ --- ┆ i64    ┆ ---    ┆ ---    ┆ ---    ┆ ---   ┆ ---   ┆ f64   ┆ lag   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ f64   ┆ ---   ┆ ---   ┆ meEst ┆ i64  ┆ ---   ┆ f64  ┆ ---   ┆ ---   ┆ amCit ┆ amId  ┆ amNam ┆ ---   ┆ f64   ┆ ---   ┆ f64   ┆ i64  ┆ ---   ┆ iatio ┆ ight  ┆ ---   ┆ f64   ┆ i64 ┆ str │
│ i64 ┆        ┆ str    ┆ str    ┆ str    ┆ f64   ┆ f64   ┆       ┆ ---   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆       ┆ f64   ┆ str   ┆ ---   ┆      ┆ str   ┆      ┆ f64   ┆ f64   ┆ y     ┆ ---   ┆ e     ┆ f64   ┆       ┆ f64   ┆       ┆      ┆ f64   ┆ n     ┆ ---   ┆ f64   ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆ i64   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   ┆      ┆       ┆      ┆       ┆       ┆ ---   ┆ i64   ┆ ---   ┆       ┆       ┆       ┆       ┆      ┆       ┆ ---   ┆ str   ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆      ┆       ┆       ┆ str   ┆       ┆ str   ┆       ┆       ┆       ┆       ┆      ┆       ┆ str   ┆       ┆       ┆       ┆     ┆     │
╞═════╪════════╪════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═════╪═════╡
│ 225 ┆ 161061 ┆ Detroi ┆ Piston ┆ Regula ┆ 0.705 ┆ 23.3  ┆ 2.38  ┆ 1     ┆ 84.2  ┆ 0.736 ┆ 84.7  ┆ 40.1  ┆ 124.7 ┆ 94.5  ┆ 0.633 ┆ 2026- ┆ 2026- ┆ 1    ┆ DET   ┆ 48.0 ┆ 42.7  ┆ 126.9 ┆ New   ┆ 16106 ┆ Knick ┆ 0.225 ┆ 94.0  ┆ 78.33 ┆ 0.708 ┆ 93   ┆ 0.516 ┆ DET   ┆ null  ┆ 0.14  ┆ 0.658 ┆ 1   ┆ W   │
│ 007 ┆ 2765   ┆ t      ┆ s      ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ York  ┆ 12752 ┆ s     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 42  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 19:30 ┆      ┆ NYK   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ Portla ┆ Trail  ┆ Regula ┆ 0.633 ┆ 20.9  ┆ 1.72  ┆ 1     ┆ 110.6 ┆ 0.735 ┆ 111.4 ┆ 16.9  ┆ 128.3 ┆ 104.2 ┆ 0.639 ┆ 2026- ┆ 2026- ┆ 1    ┆ POR   ┆ 48.0 ┆ 19.2  ┆ 129.8 ┆ Memph ┆ 16106 ┆ Grizz ┆ 0.31  ┆ 104.0 ┆ 86.67 ┆ 0.578 ┆ 104  ┆ 0.538 ┆ POR   ┆ null  ┆ 0.173 ┆ 0.68  ┆ 1   ┆ W   │
│ 007 ┆ 2757   ┆ nd     ┆ Blazer ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ is    ┆ 12763 ┆ lies  ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 45  ┆        ┆        ┆ s      ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆ MEM   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ New    ┆ Pelica ┆ Regula ┆ 0.674 ┆ 21.2  ┆ 1.81  ┆ 1     ┆ 118.6 ┆ 0.61  ┆ 119.2 ┆ 0.1   ┆ 119.4 ┆ 98.1  ┆ 0.631 ┆ 2026- ┆ 2026- ┆ 0    ┆ NOP @ ┆ 48.0 ┆ 4.1   ┆ 122.7 ┆ Minne ┆ 16106 ┆ Timbe ┆ 0.282 ┆ 97.0  ┆ 80.83 ┆ 0.54  ┆ 97   ┆ 0.48  ┆ NOP   ┆ null  ┆ 0.165 ┆ 0.663 ┆ 1   ┆ W   │
│ 007 ┆ 2740   ┆ Orlean ┆ ns     ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ MIN   ┆      ┆       ┆       ┆ sota  ┆ 12750 ┆ rwolv ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 44  ┆        ┆ s      ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 20:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆ es    ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ LA     ┆ Clippe ┆ Regula ┆ 0.595 ┆ 16.9  ┆ 1.38  ┆ 1     ┆ 114.4 ┆ 0.679 ┆ 110.3 ┆ 6.3   ┆ 116.5 ┆ 99.3  ┆ 0.585 ┆ 2026- ┆ 2026- ┆ 0    ┆ LAC @ ┆ 48.0 ┆ 0.7   ┆ 115.2 ┆ Sacra ┆ 16106 ┆ Kings ┆ 0.225 ┆ 98.0  ┆ 81.67 ┆ 0.537 ┆ 99   ┆ 0.484 ┆ LAC   ┆ null  ┆ 0.162 ┆ 0.656 ┆ 1   ┆ W   │
│ 007 ┆ 2746   ┆        ┆ rs     ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ SAC   ┆      ┆       ┆       ┆ mento ┆ 12758 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 46  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ Indian ┆ Pacers ┆ Regula ┆ 0.743 ┆ 20.6  ┆ 2.89  ┆ 1     ┆ 114.1 ┆ 0.654 ┆ 108.7 ┆ -1.3  ┆ 107.3 ┆ 94.4  ┆ 0.519 ┆ 2026- ┆ 2026- ┆ 0    ┆ IND @ ┆ 48.0 ┆ -7.7  ┆ 106.5 ┆ Milwa ┆ 16106 ┆ Bucks ┆ 0.152 ┆ 92.5  ┆ 77.08 ┆ 0.513 ┆ 93   ┆ 0.418 ┆ IND   ┆ null  ┆ 0.097 ┆ 0.561 ┆ 0   ┆ L   │
│ 007 ┆ 2754   ┆ a      ┆        ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ MIL   ┆      ┆       ┆       ┆ ukee  ┆ 12749 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 43  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 20:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ …   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …    ┆ …     ┆ …    ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …    ┆ …     ┆ …     ┆ …     ┆ …     ┆ …     ┆ …   ┆ …   │
│ 125 ┆ 161061 ┆ New    ┆ Pelica ┆ Presea ┆ 0.5   ┆ 14.4  ┆ 1.25  ┆ 1     ┆ 95.1  ┆ 0.667 ┆ 92.6  ┆ 10.8  ┆ 103.3 ┆ 104.2 ┆ 0.489 ┆ 2025- ┆ 2025- ┆ 1    ┆ NOP   ┆ 48.0 ┆ 9.8   ┆ 104.9 ┆ Melbo ┆ 15016 ┆ Unite ┆ 0.321 ┆ 102.0 ┆ 85.0  ┆ 0.555 ┆ 102  ┆ 0.5   ┆ NOP   ┆ null  ┆ 0.157 ┆ 0.532 ┆ 1   ┆ W   │
│ 000 ┆ 2740   ┆ Orlean ┆ ns     ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-03 ┆ 10-03 ┆      ┆ vs.   ┆      ┆       ┆       ┆ urne  ┆       ┆ d     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 09  ┆        ┆ s      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 5:30: ┆      ┆ MEL   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ 00    ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 15016  ┆ Melbou ┆ United ┆ Presea ┆ 0.639 ┆ 16.0  ┆ 1.28  ┆ 1     ┆ 104.9 ┆ 0.679 ┆ 103.3 ┆ -10.8 ┆ 92.6  ┆ 104.2 ┆ 0.462 ┆ 2025- ┆ 2025- ┆ 0    ┆ MEL @ ┆ 48.0 ┆ -9.8  ┆ 95.1  ┆ New   ┆ 16106 ┆ Pelic ┆ 0.333 ┆ 102.0 ┆ 85.0  ┆ 0.445 ┆ 102  ┆ 0.5   ┆ MEL   ┆ null  ┆ 0.176 ┆ 0.486 ┆ 0   ┆ L   │
│ 000 ┆        ┆ rne    ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-03 ┆ 10-03 ┆      ┆ NOP   ┆      ┆       ┆       ┆ Orlea ┆ 12740 ┆ ans   ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 09  ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 5:30: ┆      ┆       ┆      ┆       ┆       ┆ ns    ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ 00    ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 161061 ┆ Los    ┆ Lakers ┆ Presea ┆ 0.435 ┆ 8.1   ┆ 0.45  ┆ 1     ┆ 100.0 ┆ 0.679 ┆ 95.9  ┆ -15.9 ┆ 80.0  ┆ 104.4 ┆ 0.351 ┆ 2025- ┆ 2025- ┆ 1    ┆ LAL   ┆ 48.0 ┆ -19.8 ┆ 80.2  ┆ Phoen ┆ 16106 ┆ Suns  ┆ 0.232 ┆ 102.0 ┆ 85.0  ┆ 0.329 ┆ 101  ┆ 0.455 ┆ LAL   ┆ null  ┆ 0.218 ┆ 0.449 ┆ 0   ┆ L   │
│ 000 ┆ 2747   ┆ Angele ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-03 ┆ 10-03 ┆      ┆ vs.   ┆      ┆       ┆       ┆ ix    ┆ 12756 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 01  ┆        ┆ s      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆ PHX   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 161061 ┆ New    ┆ Knicks ┆ Presea ┆ 0.543 ┆ 13.4  ┆ 1.12  ┆ 1     ┆ 82.4  ┆ 0.736 ┆ 82.3  ┆ 14.7  ┆ 97.0  ┆ 102.1 ┆ 0.429 ┆ 2025- ┆ 2025- ┆ 1    ┆ NYK @ ┆ 48.0 ┆ 15.7  ┆ 98.0  ┆ Phila ┆ 16106 ┆ 76ers ┆ 0.349 ┆ 101.5 ┆ 84.58 ┆ 0.571 ┆ 101  ┆ 0.526 ┆ NYK   ┆ null  ┆ 0.168 ┆ 0.471 ┆ 1   ┆ W   │
│ 000 ┆ 2752   ┆ York   ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-02 ┆ 10-02 ┆      ┆ PHI   ┆      ┆       ┆       ┆ delph ┆ 12755 ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 08  ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 12:00 ┆      ┆       ┆      ┆       ┆       ┆ ia    ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 125 ┆ 161061 ┆ Philad ┆ 76ers  ┆ Presea ┆ 0.63  ┆ 12.8  ┆ 0.85  ┆ 1     ┆ 98.0  ┆ 0.651 ┆ 97.0  ┆ -14.7 ┆ 82.3  ┆ 102.1 ┆ 0.365 ┆ 2025- ┆ 2025- ┆ 0    ┆ PHI @ ┆ 48.0 ┆ -15.7 ┆ 82.4  ┆ New   ┆ 16106 ┆ Knick ┆ 0.264 ┆ 101.5 ┆ 84.58 ┆ 0.429 ┆ 102  ┆ 0.474 ┆ PHI   ┆ null  ┆ 0.196 ┆ 0.456 ┆ 0   ┆ L   │
│ 000 ┆ 2755   ┆ elphia ┆        ┆ son    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 10-02 ┆ 10-02 ┆      ┆ NYK   ┆      ┆       ┆       ┆ York  ┆ 12752 ┆ s     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 08  ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 12:00 ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
└─────┴────────┴────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴─────┴─────┘

### Creamos el Dataframe para limpiarlo

In [16]:
df_team_stats = lf.collect()
df_team_stats.head(2)

shape: (2, 38)
┌─────┬────────┬────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬──────┬───────┬───────┬───────┬───────┬───────┬─────┬─────┐
│ gam ┆ teamId ┆ teamCi ┆ teamNa ┆ gameTy ┆ astPc ┆ astRa ┆ astTo ┆ avail ┆ defRa ┆ drebP ┆ eDefR ┆ eNetR ┆ eOffR ┆ ePace ┆ efgPc ┆ gameD ┆ gameD ┆ home ┆ match ┆ min  ┆ netRa ┆ offRa ┆ oppon ┆ oppon ┆ oppon ┆ orebP ┆ pace  ┆ paceP ┆ pie   ┆ poss ┆ rebPc ┆ teamA ┆ teamN ┆ tmTov ┆ tsPct ┆ win ┆ wl  │
│ eId ┆ ---    ┆ ty     ┆ me     ┆ pe     ┆ t     ┆ tio   ┆ ---   ┆ ableF ┆ ting  ┆ ct    ┆ ating ┆ ating ┆ ating ┆ ---   ┆ t     ┆ ate   ┆ ateTi ┆ ---  ┆ up    ┆ ---  ┆ ting  ┆ ting  ┆ entTe ┆ entTe ┆ entTe ┆ ct    ┆ ---   ┆ er40  ┆ ---   ┆ ---  ┆ t     ┆ bbrev ┆ ame_r ┆ Pct   ┆ ---   ┆ --- ┆ --- │
│ --- ┆ i64    ┆ ---    ┆ ---    ┆ ---    ┆ ---   ┆ ---   ┆ f64   ┆ lag   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ f64   ┆ ---   ┆ ---   ┆ meEst ┆ i64  ┆ ---   ┆ f64  ┆ ---   ┆ ---   ┆ amCit ┆ amId  ┆ amNam ┆ ---   ┆ f64   ┆ ---   ┆ f64   ┆ i64  ┆ ---   ┆ iatio ┆ ight  ┆ ---   ┆ f64   ┆ i64 ┆ str │
│ i64 ┆        ┆ str    ┆ str    ┆ str    ┆ f64   ┆ f64   ┆       ┆ ---   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆       ┆ f64   ┆ str   ┆ ---   ┆      ┆ str   ┆      ┆ f64   ┆ f64   ┆ y     ┆ ---   ┆ e     ┆ f64   ┆       ┆ f64   ┆       ┆      ┆ f64   ┆ n     ┆ ---   ┆ f64   ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆ i64   ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   ┆      ┆       ┆      ┆       ┆       ┆ ---   ┆ i64   ┆ ---   ┆       ┆       ┆       ┆       ┆      ┆       ┆ ---   ┆ str   ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆      ┆       ┆       ┆ str   ┆       ┆ str   ┆       ┆       ┆       ┆       ┆      ┆       ┆ str   ┆       ┆       ┆       ┆     ┆     │
╞═════╪════════╪════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═════╪═════╡
│ 225 ┆ 161061 ┆ Detroi ┆ Piston ┆ Regula ┆ 0.705 ┆ 23.3  ┆ 2.38  ┆ 1     ┆ 84.2  ┆ 0.736 ┆ 84.7  ┆ 40.1  ┆ 124.7 ┆ 94.5  ┆ 0.633 ┆ 2026- ┆ 2026- ┆ 1    ┆ DET   ┆ 48.0 ┆ 42.7  ┆ 126.9 ┆ New   ┆ 16106 ┆ Knick ┆ 0.225 ┆ 94.0  ┆ 78.33 ┆ 0.708 ┆ 93   ┆ 0.516 ┆ DET   ┆ null  ┆ 0.14  ┆ 0.658 ┆ 1   ┆ W   │
│ 007 ┆ 2765   ┆ t      ┆ s      ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ York  ┆ 12752 ┆ s     ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 42  ┆        ┆        ┆        ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 19:30 ┆      ┆ NYK   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 225 ┆ 161061 ┆ Portla ┆ Trail  ┆ Regula ┆ 0.633 ┆ 20.9  ┆ 1.72  ┆ 1     ┆ 110.6 ┆ 0.735 ┆ 111.4 ┆ 16.9  ┆ 128.3 ┆ 104.2 ┆ 0.639 ┆ 2026- ┆ 2026- ┆ 1    ┆ POR   ┆ 48.0 ┆ 19.2  ┆ 129.8 ┆ Memph ┆ 16106 ┆ Grizz ┆ 0.31  ┆ 104.0 ┆ 86.67 ┆ 0.578 ┆ 104  ┆ 0.538 ┆ POR   ┆ null  ┆ 0.173 ┆ 0.68  ┆ 1   ┆ W   │
│ 007 ┆ 2757   ┆ nd     ┆ Blazer ┆ r      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 02-06 ┆ 02-06 ┆      ┆ vs.   ┆      ┆       ┆       ┆ is    ┆ 12763 ┆ lies  ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│ 45  ┆        ┆        ┆ s      ┆ Season ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ T00:0 ┆ 22:00 ┆      ┆ MEM   ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
│     ┆        ┆        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0:00  ┆ :00   ┆      ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆      ┆       ┆       ┆       ┆       ┆       ┆     ┆     │
└─────┴────────┴────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴──────┴───────┴───────┴───────┴───────┴───────┴─────┴─────┘